#!/bin/sh


FILES=$(find src -iname "*.java")

rm -rf bin
mkdir -p bin

for file in $FILES
do
    echo "compiling $file"
    javac -cp "./src/" -d bin $file
    if [ $? -ne 0 ]
    then
        exit 1
    fi
done

echo "done"
